[package]
name = "brados"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "brados"
test = false
bench = false

[dependencies]
uefi = "0.36.1"
egui = "0.33"
tiny-skia = { version = "0.11", default-features = false, features = ["no-std-float", "std"] }
embedded-graphics = "0.8.1"
